# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cool Engineering Stuff!
email: barret@nobel.engineering
description: >- # this means to ignore newlines until "baseurl:"
    Just some random thoughts and projects from a budding machine learning engineer on Long Island.
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://barret.nobel.engineering' # the base hostname & protocol for your site, e.g. http://example.com
github_username: frankTurtle

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
whitelist:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
compress_html:
  clippings: all
  ignore:
    envs: development

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/

defaults:
    # _posts
    - scope:
          path: ''
          type: posts
      values:
          layout: single
          read_time: true
          comments: false
          share: true
          related: true
          author_profile: true
    # _pages
    - scope:
          path: ''
          type: pages
      values:
          layout: single
          author_profile: true
    # _portfolio
    - scope:
          path: ''
          type: portfolio
      values:
          layout: single
          author_profile: false
          share: true
    # _books
    - scope:
          path: ''
          type: books
      values:
          layout: single
          author_profile: false
          share: true

# Changing the skin
minimal_mistakes_skin: 'dark' # "air", "aqua", "contrast", "dark"

author:
    name: 'Barret J. Nobel'
    avatar: '/assets/profile-me.jpg'
    bio: 'Amateur fitness guy by morning, software engineer by day, and graduate student by night.'
    location: 'Long Island, NY'
    links:
        - label: 'GitHub'
          icon: 'fab fa-fw fa-github'
          url: 'https://github.com/frankTurtle'
        - label: 'Email'
          icon: 'fas fa-fw fa-envelope-square'
          url: 'mailto:barret@nobel.engineering'
        - label: 'Lichess'
          icon: 'fas fa-fw fa-chess'
          url: 'https://lichess.org/@/franklinturtle'
        - label: 'EA Hub'
          icon: 'fas fa-lightbulb'
          url: 'https://eahub.org/profile/barret'

footer:
    links:
        - label: 'GitHub'
          icon: 'fab fa-fw fa-github'
          url: 'https://github.com/frankTurtle'
        - label: 'Email'
          icon: 'fas fa-fw fa-envelope-square'
          url: 'mailto:barret@nobel.engineering'
        - label: 'Lichess'
          icon: 'fas fa-fw fa-chess'
          url: 'https://lichess.org/@/franklinturtle'
        - label: 'EA Hub'
          icon: 'fas fa-lightbulb'
          url: 'https://eahub.org/profile/barret'

paginate: 5
paginate_path: "/posts:num/"

timezone: America/New_York

compress_html:
    clippings: all
    ignore:
        envs: development # disable compression in dev environment

# So Jekyll can see all the pages
include: ['_pages']

# Collections
collections:
    portfolio:
        output: true
        permalink: /:collection/:path/
    books:
        output: true
        permalink: /:collection/:path/
    posts:
        output: true
        permalink: /:collection/:path/
